# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtBKsKFEUuKLZhtEomU6rJagaV4LnL8C

**Install Libraries**
"""

!pip -q install pandas numpy matplotlib seaborn scikit-learn

"""**Import Libraries**"""

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

sns.set(style='whitegrid')
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

"""**Upload Dataset**

Upload the CSV file from Kaggle when prompted.
"""

from google.colab import files

uploaded = files.upload()

csv_name = next(iter(uploaded))

df = pd.read_csv(io.BytesIO(uploaded[csv_name]))

df.head()

"""**Quick Inspection**"""

print('Shape:', df.shape)

display(df.head())

df.info()

display(df.describe(include='all').T)

"""**Check Columns**"""

print('Columns:', df.columns.tolist())

"""**Data Cleaning**"""

df = df.copy()

df.columns = [c.strip().lower() for c in df.columns]

df = df.drop_duplicates()

for col in df.columns:
    if col != 'country':
        df[col] = pd.to_numeric(df[col], errors='coerce')

numeric_cols = [c for c in df.columns if c != 'country']

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

df.isna().sum()

"""**Correlation Heatmap**"""

plt.figure(figsize=(12, 8))

sns.heatmap(
    df.select_dtypes(include=np.number).corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap')

plt.show()

"""**Boxplots**"""

for col in numeric_cols:

    plt.figure(figsize=(8, 3))

    sns.boxplot(x=df[col])

    plt.title(f'Boxplot: {col}')

    plt.show()

"""**Feature Scaling**

Clustering works better when features are on the same scale.
"""

features = df.drop(
    columns=['country'],
    errors='ignore'
)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(features)

X_scaled.shape

"""**Elbow Method**"""

inertias = []

k_values = range(2, 11)

for k in k_values:

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    model.fit(X_scaled)

    inertias.append(model.inertia_)

"""**Plot Elbow Curve**"""

plt.figure(figsize=(8, 4))

plt.plot(
    list(k_values),
    inertias,
    marker='o'
)

plt.title('Elbow Method')

plt.xlabel('Number of clusters')

plt.ylabel('Inertia')

plt.show()

"""**Train K-Means**"""

best_k = 3

kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

df['kmeans_cluster'] = kmeans.fit_predict(
    X_scaled
)

print(
    'Silhouette Score:',
    silhouette_score(
        X_scaled,
        df['kmeans_cluster']
    )
)

df[['country', 'kmeans_cluster']].head()

"""**DBSCAN**"""

dbscan = DBSCAN(
    eps=1.5,
    min_samples=5
)

df['dbscan_cluster'] = dbscan.fit_predict(
    X_scaled
)

print(
    df['dbscan_cluster']
    .value_counts()
    .sort_index()
)

"""**PCA**"""

pca = PCA(
    n_components=2,
    random_state=42
)

X_pca = pca.fit_transform(
    X_scaled
)

"""**PCA Visualization**"""

viz = pd.DataFrame({
    'pca1': X_pca[:, 0],
    'pca2': X_pca[:, 1],
    'cluster': df['kmeans_cluster']
})

plt.figure(figsize=(8, 6))

sns.scatterplot(
    data=viz,
    x='pca1',
    y='pca2',
    hue='cluster',
    palette='tab10'
)

plt.title(
    'K-Means Clusters Visualized with PCA'
)

plt.show()

"""**Cluster Profiling**"""

profile = (
    df.groupby('kmeans_cluster')
    [numeric_cols]
    .mean()
    .round(2)
)

profile

"""**Final Insights**
1. Cluster 1 has the highest child mortality rate (92.96) and the lowest life expectancy (59.19 years), indicating poor healthcare and living conditions.

2. Cluster 0 has the highest income (45,672.22) and GDP per capita (42,494.44), representing highly developed countries with better economic and social indicators.

3. Cluster 1 appears to be the most underdeveloped cluster because it has the lowest income (3,942.40), lowest GDP per capita (1,922.38), highest child mortality, and highest fertility rate (5.01).

4. Countries belonging to Cluster 1 should be prioritized for international aid and development programs as they face significant economic and healthcare challenges.

5. Cluster 2 represents developing countries with moderate income (12,305.60), GDP per capita (6,486.45), and life expectancy (72.81), placing them between developed and underdeveloped nations.

**Direct Answers**
1. Which cluster has high child mortality? → Cluster 1
2. Which cluster has high income and gdpp? → Cluster 0
3. Which cluster looks underdeveloped? → Cluster 1
4. Which countries should be prioritized for aid? → Countries in Cluster 1
"""